spring.application.name=ymmo

# server configuration
server.servlet.context-path=/api

# jpa database configuration
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# jwt configuration
jwt.secretKey=${JWT_SECRET}
jwt.expiration=3600000